In [13]:
import numpy as NP
array=NP.array([5,6,7], dtype='float32')
print("Array",array)
twoDarray=NP.array([[5,6,7,8],[9,10,7,6]],dtype='float64')
print("2DArray",twoDarray)
#get dimension of arrays
print('Dimensionality',twoDarray.ndim)
print('Dimensionality',array.ndim)
print('shape=',array.shape)
print('shape=',twoDarray.ndim)
print('Datatype2=',twoDarray.dtype)
print('Datatype1=',array.dtype)
a=twoDarray.size
b=array.size
print(a)
print(b)
c=array.itemsize
c1=array.nbytes
print(c)
print(c1)
d=twoDarray.itemsize
d1=twoDarray.nbytes
print(d)
print(d1)
threeDarray=NP.array([[[5,6,7,8],[9,10,7,6]],[[1,2,3,4],[4,9,5,2]]],dtype='int16')
print(threeDarray)
print('3darray size=',threeDarray.size)
threeDarray.shape
#accessing row column, elemnets
print(twoDarray[0,2:4])
print(twoDarray[0,:])
print(twoDarray[:,1])
print(twoDarray[:,2])

Array [5. 6. 7.]
2DArray [[ 5.  6.  7.  8.]
 [ 9. 10.  7.  6.]]
Dimensionality 2
Dimensionality 1
shape= (3,)
shape= 2
Datatype2= float64
Datatype1= float32
8
3
4
12
8
64
[[[ 5  6  7  8]
  [ 9 10  7  6]]

 [[ 1  2  3  4]
  [ 4  9  5  2]]]
3darray size= 16
[7. 8.]
[5. 6. 7. 8.]
[ 6. 10.]
[7. 7.]


### Accessing Specific Elements Rows or Columns

In [14]:
import numpy as NP
threeDarray=NP.array([[[5,6,7,8],[9,10,7,6]],[[1,2,3,4],[4,9,5,2]]],dtype='int16')
print(threeDarray)
print(threeDarray[0,1,3]) #for 6of 5678 page,row,column
print(threeDarray[1,0,1]) #2 of 1234
testmat=NP.array([[1,2,3,4,5,6,7,8,9,0],[0,9,8,7,6,5,4,3,2,1],[4,5,6,7,8,9,0,1,2,3],[3,2,1,0,9,8,7,6,5,4]])
print(testmat)
testmat[0:2, ]

[[[ 5  6  7  8]
  [ 9 10  7  6]]

 [[ 1  2  3  4]
  [ 4  9  5  2]]]
6
2
[[1 2 3 4 5 6 7 8 9 0]
 [0 9 8 7 6 5 4 3 2 1]
 [4 5 6 7 8 9 0 1 2 3]
 [3 2 1 0 9 8 7 6 5 4]]
